### ISSUE TITLE
Change getFilesRecursive() in runner.js to get the files with a glob

### ISSUE THREAD

**Issue by NJKode** [CloudCannon/reseed#13]
This would be a lot simpler and easier than the current implementation.
Thought I would open this up for a beginner, in the spirit of hacktober :) 

NB:  Fair attempts are more than welcome! Garbage submissions will be reported.

**Comment by NJKode** [comment]
(Possible) hint: Using a node package is fine.

**Comment by sdhiman99** [comment]
Hi! I'd like to take this up.
